### ISSUE TITLE
MissUnderstanding filter in bfs size

### ISSUE THREAD

**Issue by fabiana001** [fabiofumarola/HyLiEn#14]
In eu.unicredit.web.hylien.ListFinder line 62:
`domNode.children.filter(_.bfs.size <= maxRecordTags)`
Why do you need to filter trees having a number of nodes lesser than maxRecordTags (i.e. 30)?

**Comment by fabiofumarola** [comment]
that like in MDR I'm considering that the records cannot have a size
greater that 30

2016-06-28 9:37 GMT+02:00 Fabiana Lanotte <notifications@github.com>:

> In ListFinder line 62:
> domNode.children.filter(_.bfs.size <= maxRecordTags)
> Why do you need to filter trees having a number of nodes lesser than
> maxRecordTags (i.e. 30)?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fabiofumarola/HyLiEn/issues/14>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABepUDYU0AdgaBqAtMQdOMDdFZsuKNcQks5qQM9HgaJpZM4I_0qX>
> .
>



-- 
______________________________________________________

Fabio Fumarola Ph.D.

Math and IT Research @ Unicredit R&D
https://www.linkedin.com/pub/fabio-fumarola/7/540/605
mailto:f <fumarola@illinois.edu>abio.fumarola@unicredit.eu
mailto:ffumarola@di.uniba.it

**Comment by fabiofumarola** [comment]
@fabiana001 have you read it?

**Comment by fabiana001** [comment]
see issue #16
