### ISSUE TITLE
Implement Tree Edit Distance for structural similarity

### ISSUE THREAD

**Issue by fabiana001** [fabiofumarola/HyLiEn#15]
You can find the java implementation in DataRecordAligner project (see [here](https://bitbucket.org/fabianaLanotte/datarecordaligner) ).
The distance was first proposed in [Web Data Extraction Based on Partial Tree Alignment](http://sisfo.upiyptk.ac.id/download/Referency%20Jurnal%20Hybrid%20(SM-STM)-12-Web%20Data%20Extraction%20Based%20on%20Partial%20Tree%20Alignment.pdf).

Tree Edit Distance is an evolution of Edit Distance and performs better for data record collections having optional items

**Comment by fabiofumarola** [comment]
Pull request with tests are welcome!

**Comment by fabiofumarola** [comment]
done
